# Generated by Django 3.2.25 on 2024-05-20 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '010-1234-5678' or '010-123-4567'.", regex='^01[016789]-\\d{3,4}-\\d{4}$')])),
                ('academic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('abstract', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(blank=True, max_length=23, validators=[django.core.validators.RegexValidator(message="Period must be entered in the format: 'YYYY-MM-DD to YYYY-MM-DD'.", regex='^\\d{4}-\\d{2}-\\d{2} to \\d{4}-\\d{2}-\\d{2}$')])),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Intern', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_activities', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(blank=True, max_length=23, validators=[django.core.validators.RegexValidator(message="Period must be entered in the format: 'YYYY-MM-DD to YYYY-MM-DD'.", regex='^\\d{4}-\\d{2}-\\d{2} to \\d{4}-\\d{2}-\\d{2}$')])),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='myapp.user')),
            ],
        ),
    ]
