# Generated by Django 3.2.25 on 2024-05-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_company_externalactivity_intern_paper_project_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
