# Generated by Django 3.2.25 on 2024-05-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
