# Generated by Django 3.2.25 on 2024-05-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240523_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalactivity',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='externalactivity',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
