# Generated by Django 3.2.25 on 2024-05-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240523_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='intern',
            old_name='name',
            new_name='intern_company_name',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='title',
            new_name='paper_title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
    ]
