# Generated by Django 3.2.25 on 2024-05-26 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20240526_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='period',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Period must be entered in the format: 'YYYY-MM-DD to YYYY-MM-DD'.", regex='^\\d{4}-\\d{2}-\\d{2} to \\d{4}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='intern',
            name='period',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Period must be entered in the format: 'YYYY-MM-DD to YYYY-MM-DD'.", regex='^\\d{4}-\\d{2}-\\d{2} to \\d{4}-\\d{2}-\\d{2}$')]),
        ),
    ]
