# Generated by Django 3.2.25 on 2024-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_intern_intern_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='period',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='period',
        ),
        migrations.AddField(
            model_name='company',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
