# Generated by Django 3.2.25 on 2024-06-11 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20240603_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '010-1234-5678' or '010-123-4567'.", regex='^01[016789]-\\d{3,4}-\\d{4}$')]),
        ),
    ]
