# Generated by Django 3.2.25 on 2024-06-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20240611_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_cv_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
