# Generated by Django 3.2.25 on 2024-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_updated_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_cv_file',
            field=models.BooleanField(default=False),
        ),
    ]
